name: Android APK Build

on:
  push:
    branches:
      - master  # Adjust to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download Godot export templates
      run: |
        wget --continue --timeout=60 --tries=10 --retry-connrefused https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
        if [ $? -ne 0 ]; then
          echo "Failed to download export templates. Exiting."
          exit 1
        fi

    - name: Create export templates directory
      run: |
        mkdir -p ~/.local/share/godot/export_templates

    - name: Rename and unzip export templates
      run: |
        mv Godot_v4.3-stable_export_templates.tpz Godot_v4.3-stable_export_templates.zip
        unzip Godot_v4.3-stable_export_templates.zip -d ~/.local/share/godot/export_templates/

    - name: Download Godot X11 build
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_x11.64.zip
        unzip Godot_v4.3-stable_linux_x11.64.zip -d godot-x11

    - name: Export Android APK
      run: |
        godot-x11/Godot_v4.3-stable_linux_x11.64 --export-debug android build/output.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: build/output.apk
