name: Android APK Build

on:
  push:
    branches:
      - master  # Changed to master as per your setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download Godot export templates
      run: |
        wget --tries=3 --retry-connrefused https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
        if [ $? -ne 0 ]; then
          echo "Failed to download export templates. Exiting."
          exit 1
        fi
        tar -xvf Godot_v4.3-stable_export_templates.tpz -C ~/.local/share/godot/export_templates/

    - name: Download Godot headless binary
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux_headless.64.zip
        unzip Godot_v4.3-stable_linux_headless.64.zip -d godot-headless

    - name: Export Android APK
      run: |
        godot-headless/Godot_v4.3-stable_linux_headless.64 --export-debug android build/output.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: build/output.apk

