name: Android APK Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot 3.6 export templates
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.6/Godot_v3.6-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates
        mv Godot_v3.6-stable_export_templates.tpz Godot_v3.6-stable_export_templates.zip
        unzip Godot_v3.6-stable_export_templates.zip -d ~/.local/share/godot/export_templates/

    - name: Download Godot 3.6 Linux server
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.6/Godot_v3.6-stable_linux_server.64.zip
        unzip Godot_v3.6-stable_linux_server.64.zip -d godot-linux

    - name: Export Android APK
      run: |
        godot-linux/Godot_v3.6-stable_linux_server.64 --export-debug android build/output.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: build/output.apk
