name: Build and Export Godot Project

on:
  push:
    branches:
      - master # Adjust if your main branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Godot
        run: |
          mkdir -p ~/godot
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip -O ~/godot/Godot_v4.3-stable_linux.x86_64.zip
          unzip ~/godot/Godot_v4.3-stable_linux.x86_64.zip -d ~/godot

      - name: Set up Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz -O ~/godot/Godot_v4.3-stable_export_templates.tpz
          cd ~/.local/share/godot/export_templates
          # Unzip if the file is actually a zip archive
          unzip ~/godot/Godot_v4.3-stable_export_templates.tpz

      - name: Set up Android SDK
        run: |
          echo "SDK Path: ${{ secrets.ANDROID_SDK_PATH }}"
          export ANDROID_HOME=${{ secrets.ANDROID_SDK_PATH }}
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          export PATH=$PATH:$ANDROID_HOME/build-tools/30.0.3

      - name: Build and Export Project
        run: |
          ~/godot/Godot_v4.3-stable_linux.x86_64 --headless --export-debug "Android" build/output.apk
