name: Build Godot Project for Android

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # Install necessary tools and libraries
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y wget unzip

      # Download Godot binary and export templates
      - name: Download Godot and export templates
        run: |
          # Download Godot binary
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip -d godot-linux

          # Download export templates
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz

          # Verify the file is not empty and is a valid .tpz file
          file Godot_v4.3-stable_export_templates.tpz

          # Create directory for export templates
          mkdir -p ~/.local/share/godot/export_templates

          # Rename tpz to zip and extract
          mv Godot_v4.3-stable_export_templates.tpz Godot_v4.3-stable_export_templates.zip
          unzip Godot_v4.3-stable_export_templates.zip -d ~/.local/share/godot/export_templates

      # Set up Android SDK (if needed, adapt as necessary)
      - name: Set up Android SDK
        run: |
          echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          sudo apt-get install -y android-sdk
          sudo apt-get install -y adb

      # Export the Godot project for Android
      - name: Export Godot Project
        run: |
          godot-linux/Godot_v4.3-stable_linux.x86_64 --headless --export-debug "Android" build/output.apk

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: output-apk
          path: build/output.apk

