name: Build Godot Android APK

on:
  push:
    branches:
      - master # Change to your default branch name if different
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Godot Linux Headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip -d godot-linux/

      - name: Download Godot Export Templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates
          mv Godot_v4.3-stable_export_templates.tpz ~/.local/share/godot/export_templates
          tar -xf ~/.local/share/godot/export_templates/Godot_v4.3-stable_export_templates.tpz -C ~/.local/share/godot/export_templates

      - name: Export Android APK
        run: |
          godot-linux/Godot_v4.3-stable_linux.x86_64 --headless --export-debug android build/output.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/output.apk
